-- MySQL Script generated by MySQL Workbench
-- Fri Aug  4 22:07:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quizzler-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quizzler-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quizzler-db` DEFAULT CHARACTER SET utf8mb3 ;
USE `quizzler-db` ;

-- -----------------------------------------------------
-- Table `quizzler-db`.`MediaType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`MediaType` (
  `MediaTypeId` INT NOT NULL AUTO_INCREMENT,
  `Extension` VARCHAR(10) NOT NULL,
  `TypeName` ENUM('Image', 'Video', 'Audio') NOT NULL,
  `MaxSize` BIGINT NOT NULL,
  PRIMARY KEY (`MediaTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(32) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `FirstName` VARCHAR(20) NULL DEFAULT NULL,
  `LastName` VARCHAR(20) NULL DEFAULT NULL,
  `DateRegistered` DATETIME NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`Media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`Media` (
  `MediaId` INT NOT NULL AUTO_INCREMENT,
  `MediaTypeId` INT NOT NULL,
  `UploaderId` INT NOT NULL,
  `Path` VARCHAR(500) NOT NULL,
  `FileSize` BIGINT NOT NULL,
  PRIMARY KEY (`MediaId`),
  INDEX `MediaTypeId_idx` (`MediaTypeId` ASC) VISIBLE,
  INDEX `UploaderId_idx` (`UploaderId` ASC) VISIBLE,
  CONSTRAINT `fk_Media_MediaTypeId`
    FOREIGN KEY (`MediaTypeId`)
    REFERENCES `quizzler-db`.`MediaType` (`MediaTypeId`),
  CONSTRAINT `fk_Media_UploaderId`
    FOREIGN KEY (`UploaderId`)
    REFERENCES `quizzler-db`.`User` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`Quiz` (
  `QuizId` INT NOT NULL AUTO_INCREMENT,
  `QuizOwner` INT NOT NULL,
  `Title` VARCHAR(40) NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `IsPublic` TINYINT(1) NOT NULL,
  `DateCreated` DATETIME NOT NULL,
  PRIMARY KEY (`QuizId`),
  INDEX `QuizOwner_idx` (`QuizOwner` ASC) VISIBLE,
  CONSTRAINT `fk_Quiz_QuizOwner`
    FOREIGN KEY (`QuizOwner`)
    REFERENCES `quizzler-db`.`User` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`Question` (
  `QuestionId` INT NOT NULL AUTO_INCREMENT,
  `QuizId` INT NOT NULL,
  `QuestionText` VARCHAR(255) NOT NULL,
  `QuestionMediaId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`QuestionId`),
  INDEX `QuizId_idx` (`QuizId` ASC) VISIBLE,
  INDEX `QuestionMediaId_idx` (`QuestionMediaId` ASC) VISIBLE,
  CONSTRAINT `fk_Question_QuestionMediaId`
    FOREIGN KEY (`QuestionMediaId`)
    REFERENCES `quizzler-db`.`Media` (`MediaId`),
  CONSTRAINT `fk_Question_QuizId`
    FOREIGN KEY (`QuizId`)
    REFERENCES `quizzler-db`.`Quiz` (`QuizId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`Answer` (
  `AnswerId` INT NOT NULL AUTO_INCREMENT,
  `QuestionId` INT NOT NULL,
  `AnswerText` VARCHAR(255) NOT NULL,
  `IsCorrect` TINYINT(1) NOT NULL,
  `AnswerMediaId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`AnswerId`),
  INDEX `QuestionId_idx` (`QuestionId` ASC) VISIBLE,
  INDEX `AnswerMediaId_idx` (`AnswerMediaId` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_AnswerMediaId`
    FOREIGN KEY (`AnswerMediaId`)
    REFERENCES `quizzler-db`.`Media` (`MediaId`),
  CONSTRAINT `fk_Answer_QuestionId`
    FOREIGN KEY (`QuestionId`)
    REFERENCES `quizzler-db`.`Question` (`QuestionId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`Lesson` (
  `LessonId` INT NOT NULL AUTO_INCREMENT,
  `LessonOwner` INT NOT NULL,
  `IsPublic` TINYINT(1) NOT NULL DEFAULT '1',
  `Title` VARCHAR(40) NOT NULL,
  `Description` VARCHAR(150) NOT NULL DEFAULT 'My lesson',
  `DateCreated` DATETIME NOT NULL,
  PRIMARY KEY (`LessonId`),
  INDEX `LessonOwner_idx` (`LessonOwner` ASC) VISIBLE,
  CONSTRAINT `fk_Lesson_LessonOwner`
    FOREIGN KEY (`LessonOwner`)
    REFERENCES `quizzler-db`.`User` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`Flashcard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`Flashcard` (
  `FlashcardId` INT NOT NULL AUTO_INCREMENT,
  `LessonId` INT NOT NULL,
  `DateCreated` DATETIME NOT NULL,
  `QuestionText` VARCHAR(200) NULL DEFAULT NULL,
  `QuestionMediaId` INT NULL DEFAULT NULL,
  `AnswerText` VARCHAR(200) NULL DEFAULT NULL,
  `AnswerMediaId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`FlashcardId`),
  INDEX `LessonId_idx` (`LessonId` ASC) VISIBLE,
  INDEX `AnswerMediaId_idx` (`AnswerMediaId` ASC) VISIBLE,
  INDEX `fk_Flashcard_QuestionMediaId_idx` (`QuestionMediaId` ASC) VISIBLE,
  CONSTRAINT `fk_Flashcard_AnswerMediaId`
    FOREIGN KEY (`AnswerMediaId`)
    REFERENCES `quizzler-db`.`Media` (`MediaId`),
  CONSTRAINT `fk_Flashcard_LessonId`
    FOREIGN KEY (`LessonId`)
    REFERENCES `quizzler-db`.`Lesson` (`LessonId`),
  CONSTRAINT `fk_Flashcard_QuestionMediaId`
    FOREIGN KEY (`QuestionMediaId`)
    REFERENCES `quizzler-db`.`Media` (`MediaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quizzler-db`.`LoginInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzler-db`.`LoginInfo` (
  `UserId` INT NOT NULL,
  `PasswordHash` CHAR(80) NULL DEFAULT NULL,
  `Salt` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `fk_LoginInfo_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `quizzler-db`.`User` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
